
services:
#  pinterest.api.users:
#    image: pinterest.api.users
#    build:
#      context: .
#      dockerfile: Pinterest.Systems/Pinterest.Api.Users/Dockerfile
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=pinterest.users
    ports:
      - "7272:5432"
    networks:
      pinterest-network:
        aliases:
          - postgres
        ipv4_address: 172.24.0.2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pinterest.users" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234567890
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    volumes:
      - "./rabbitmq-data:/var/lib/rabbitmq"
    networks:
      pinterest-network:
        aliases:
          - rabbitmq
        ipv4_address: 172.24.0.3
        
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      pinterest-network:
        aliases:
          - minio
        ipv4_address: 172.24.0.4
    volumes:
      - "./minio-data/data:/data"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=1234567890
      - MINIO_DEFAULT_BUCKETS=models
    restart: always
    command: server /data --console-address :9001

networks:
  pinterest-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - gateway: 172.24.0.1
          subnet: 172.24.0.0/24
        
